//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpAccMappTable
    {
        public int ZaposlenikID { get; set; }
        public int AccID { get; set; }
        public string Opis { get; set; }
    
        public virtual AccountTable AccountTable { get; set; }
    }
}
