//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BazaAccountManEntities : DbContext
    {
        public BazaAccountManEntities()
            : base("name=BazaAccountManEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountTable> AccountTables { get; set; }
        public virtual DbSet<AccRoleMappTable> AccRoleMappTables { get; set; }
        public virtual DbSet<EmpAccMappTable> EmpAccMappTables { get; set; }
        public virtual DbSet<RoleTable> RoleTables { get; set; }
    }
}
