//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleTable
    {
        public RoleTable()
        {
            this.AccRoleMappTables = new HashSet<AccRoleMappTable>();
        }
    
        public int RoleID { get; set; }
        public string ImeRole { get; set; }
    
        public virtual ICollection<AccRoleMappTable> AccRoleMappTables { get; set; }
    }
}
