//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountAssignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountTable
    {
        public AccountTable()
        {
            this.EmpAccMappTables = new HashSet<EmpAccMappTable>();
        }
    
        public int AccID { get; set; }
        public string ImeAcc { get; set; }
        public string TipAcc { get; set; }
        public Nullable<System.DateTime> Kreirano { get; set; }
        public Nullable<System.DateTime> Izmjena { get; set; }
    
        public virtual ICollection<EmpAccMappTable> EmpAccMappTables { get; set; }
    }
}
