//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTable
    {
        public EmployeeTable()
        {
            this.EmpAccMappTables = new HashSet<EmpAccMappTable>();
        }
    
        public int ZaposlenikID { get; set; }
        public string ImeZap { get; set; }
        public string PrezimeZap { get; set; }
        public System.DateTime DatumRodenja { get; set; }
        public string AdresaZap { get; set; }
        public string GradZap { get; set; }
        public int RoleID { get; set; }
    
        public virtual ICollection<EmpAccMappTable> EmpAccMappTables { get; set; }
        public virtual RoleTable RoleTable { get; set; }
    }
}
